# Header

menu:
  ä¸»é¡µ: /
  #ç›¸å†Œ: /photos

# SubNav
subnav:
  github: "https://github.com/YoobinLee"
  #weibo: "http://weibo.com/litten225"
  #rss: /atom.xml
  #psn: "#"
  #zhihu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:cuichunji0508@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://www.linkedin.com/in/chunji-cui-976095292/"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: 

# Content
excerpt_link: 'more'
show_all_link: 'å±•å¼€å…¨æ–‡'
fancybox: true
mathjax: false

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 0
reward_wording: 'è°¢è°¢ä½ è¯·æˆ‘åƒç³–æœ'
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixin.jpg

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 1
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#ä½ çš„å¤´åƒurl
avatar: /img/summerpalace.jpg

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

mobile:
  social: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqus ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#è¯·å‚è€ƒwikiï¼š

#1ã€å¤šè¯´
#duoshuo: "litten-hexo"

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3ã€ç•…è¨€
changyan_appid: 'cysX3aGWt'
changyan_conf: 'prod_1dcda447175aada96edcdb7e412338fa'

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  # ä¸»è¦æ˜¯è¿™ä¸€éƒ¨åˆ†
  updated_at:
    # æ˜¾ç¤ºæ›´æ–°æ—¶é—´
    enable: true
    # ä¸åˆ›å»ºæ—¶é—´ä¸åŒæ—¶æ‰æ˜¾ç¤º
    another_day: true
  categories: true

# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæˆ‘'

friends:
  Leo's blog: https://leoleoasd.me/

aboutme: BJUT CS<br>Bachelor's degree 2019 - 2023<br> KAIST AI <br>Master student 2023 - <br> <br>Hobbit LoverğŸ˜